### ISSUE TITLE
Update GitHub Repo Description

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/cherry_blossom_tracker_R#4]
Please modify your GitHub repo description in the top right corner where it says “About” to include

A short description of your app (might already be there)

The link to your deployed dashboard (it is often useful to still keep this in the README as well)

A few keywords describing which plots, widgets, and interactions you have used in your dashboards, [like it has been done this demo app](https://github.com/UBC-MDS/dashr-heroku-deployment-demo).

**Comment by gfairbro** [comment]
Complete
